import { Project } from '../types/project'

// Phase 1: Mock data that mirrors the exact structure needed for Phase 2+
export const mockProjects: Project[] = [
  {
    id: 'shakespeare-chatbot',
    title: '(Uni) Shakespeare Literature Chatbot',
    shortDescription: 'Built a domain specific intelligent chatbot to answer questions about Shakespeare\'s plays.',
    fullDescription: 'Developed an advanced chatbot using small language models and RAG (Retrieval-Augmented Generation) to provide accurate, contextual answers about Shakespeare\'s literary works. The system combines fine-tuning techniques with efficient retrieval systems.',
    category: 'academic',
    projectCategory: 'data-ml',
    technologies: ['Python', 'DistilGPT-2', 'GPT-Neo', 'TinyLlama', 'LoRA', 'RAG', 'Streamlit'],
    githubUrl: 'https://github.com/id-nynt/250021_shakespeare-chatbot',
    projectUrl: 'https://250021shakespeare-chatbot.streamlit.app/',
    team: '3-person team',
    role: 'Team Coordinator & Technical Lead',
    responsibilities: [
      'Coordinated team workflow and technical decisions',
      'Automated text cleaning, scene summarisation, and metadata extraction',
      'Fine-tuned multiple language models using LoRA',
      'Implemented RAG system for fast, accurate retrieval'
    ],
    outcomes: [
      'Delivered functional Shakespearean chatbot',
      'Successfully fine-tuned TinyLlama + RAG pipeline',
      'Achieved accurate factual query responses'
    ],
    period: '03/2025 - 06/2025',
    imageUrl: '/images/projects/shakespeare-chatbot.png',
    featured: true,
    status: 'completed'
  },
  {
    id: 'portfolio-website',
    title: 'Personal Portfolio Website',
    shortDescription: 'Built a fully responsive portfolio to showcase skills, resume, and projects.',
    fullDescription: 'Created a modern, responsive portfolio website using React and Next.js with a focus on performance, SEO, and user experience. Features dynamic project filtering, contact forms, and optimized image delivery.',
    category: 'professional',
    projectCategory: 'software',
    technologies: ['React', 'Next.js', 'TailwindCSS', 'TypeScript', 'AWS'],
    githubUrl: 'https://github.com/id-nynt/250020_Profile-Web',
    //projectUrl: 'https://250020-profile-web.vercel.app/',
    team: 'Individual project',
    role: 'Full-stack Developer',
    responsibilities: [
      'Developed reusable UI components with modern design practices',
      'Integrated project highlights and downloadable resume',
      'Implemented responsive design for all devices',
      'Deployed on AWS for high availability'
    ],
    outcomes: [
      'Mobile-friendly personal site accessible across devices',
      'Professional online presence for job applications',
      'Showcased technical skills and project portfolio'
    ],
    period: '11/2025 - 12/2025',
    imageUrl: '/images/projects/portfolio-website.png',
    featured: true,
    status: 'completed'
  },
  {
    id: 'egovernment-microservice',
    title: '(Uni) E-government Microservice Platform',
    shortDescription: 'Developed a microservice-based government service portal in a 6-member team.',
    fullDescription: 'Architected and implemented a scalable e-government platform using microservices architecture. The system handles multiple government services through independent, containerized services with API gateway integration.',
    category: 'academic',
    projectCategory: 'software',
    technologies: ['C#', 'ASP.NET', 'Docker', 'API Gateway', 'Microservices'],
    githubUrl: 'https://github.com/id-nynt/250019_Microservice-E-gov-Platform',
    team: '6-member team',
    role: 'Project Coordinator',
    responsibilities: [
      'Coordinated project planning and requirement analysis',
      'Built two independent microservices',
      'Integrated four services via ASP.NET API Gateway',
      'Containerized services with Docker'
    ],
    outcomes: [
      'Platform successfully executed in local environments',
      'Demonstrated microservice architecture principles',
      'Effective team coordination and delivery'
    ],
    period: '09/2025 - 11/2025',
    imageUrl: '/images/projects/egovernment-platform.png',
    featured: false,
    status: 'completed'
  },
  {
    id: 'big-data-analytics',
    title: '(Uni) Big Data Analytics for ImageNet Classification',
    shortDescription: 'Conducted large-scale analytics using ImageNet features generated by EVA-02.',
    fullDescription: 'Performed comprehensive big data analysis on ImageNet classification tasks using advanced machine learning techniques. Implemented efficient data pipelines and achieved significant performance improvements through hyperparameter optimization.',
    category: 'academic',
    projectCategory: 'data-ml',
    technologies: ['Python', 'XgBoost', 'ImageNet', 'EVA-02', 'Data Analytics', 'Machine Learning'],
    githubUrl: 'https://github.com/id-nynt/250022_imagenet_analysis',
    team: 'Academic project',
    role: 'Data Scientist',
    responsibilities: [
      'Analysed requirements and designed end-to-end pipeline',
      'Performed data preprocessing and EDA',
      'Implemented baseline ImageNet classifier using XgBoost',
      'Hyperparameter tuning and model optimization'
    ],
    outcomes: [
      'Achieved 86.86% and 76.47% accuracy',
      'Reduced performance gap from 10.39% to 7.56%',
      'Received commendation for "high technical maturity"'
    ],
    period: '10/2025 - 11/2025',
    imageUrl: '/images/projects/big-data-analytics.png',
    featured: true,
    status: 'completed'
  },
  {
    id: 'aws-serverless-data-lake',
    title: 'AWS Serverless Data Lake Workshop',
    shortDescription: 'Hands-on serverless data lake development using AWS cloud-native tools.',
    fullDescription: 'Built a comprehensive serverless data lake architecture using AWS services. Implemented automated data ingestion, transformation, and querying capabilities with cloud-native tools and infrastructure as code.',
    category: 'professional',
    projectCategory: 'cloud-networking',
    technologies: ['AWS', 'CloudFormation', 'IAM', 'AWS Glue', 'S3', 'Athena'],
    githubUrl: 'https://github.com/id-nynt/250016_aws-serverless-lake-day',
    team: 'Individual workshop',
    role: 'Cloud Developer',
    responsibilities: [
      'Used CloudFormation and IAM roles for infrastructure provisioning',
      'Performed ETL and metadata cataloguing with AWS Glue',
      'Queried global datasets using Athena',
      'Built serverless data pipeline'
    ],
    outcomes: [
      'Built fully serverless GDELT ingestion + transform + query pipeline',
      'Gained hands-on AWS cloud experience',
      'Understanding of serverless architecture patterns'
    ],
    period: '09/2025 - 10/2025',
    imageUrl: '/images/projects/aws-data-lake.png',
    featured: false,
    status: 'completed'
  },
  {
    id: 'aws-101-workshop',
    title: 'AWS 101 Workshop',
    shortDescription: 'Hands-on introduction to AWS cloud services and infrastructure.',
    fullDescription: 'Comprehensive introduction to Amazon Web Services covering fundamental concepts, core services, and hands-on practice with cloud infrastructure deployment and management.',
    category: 'professional',
    projectCategory: 'cloud-networking',
    technologies: ['AWS', 'Cloud Computing', 'Infrastructure'],
    githubUrl: 'https://github.com/id-nynt/250015_aws-101-workshop',
    team: 'Individual workshop',
    role: 'Cloud Student',
    responsibilities: [
      'Learned fundamental AWS services and concepts',
      'Hands-on practice with EC2, S3, and other core services',
      'Understanding cloud architecture principles',
      'Completed practical exercises and labs'
    ],
    outcomes: [
      'Gained foundational knowledge of AWS cloud services',
      'Practical experience with cloud infrastructure',
      'Preparation for advanced AWS workshops'
    ],
    period: '08/2025 - 09/2025',
    imageUrl: '/images/projects/aws-101.png',
    featured: false,
    status: 'completed'
  },
  {
    id: 'healthcare-network-design',
    title: '(Uni) Healthcare Network Design',
    shortDescription: 'Designed a realistic network architecture for a healthcare facility.',
    fullDescription: 'Comprehensive network design project for a healthcare facility, including security considerations, compliance requirements, and scalable infrastructure planning for medical data management.',
    category: 'academic',
    projectCategory: 'cloud-networking',
    technologies: ['Network Design', 'Infrastructure Planning', 'Documentation'],
    githubUrl: 'https://github.com/id-nynt/Healthcare-Network-System',
    team: 'Academic team project',
    role: 'Project Lead',
    responsibilities: [
      'Led project planning and coordination',
      'Analysed infrastructure requirements',
      'Explained networking challenges to team members',
      'Structured and delivered technical presentation'
    ],
    outcomes: [
      'Scored 98/100 for outstanding design and communication',
      'Demonstrated network architecture expertise',
      'Effective technical communication skills'
    ],
    period: '08/2024 - 10/2024',
    imageUrl: '/images/projects/healthcare-network.png',
    featured: false,
    status: 'completed'
  },
  {
    id: 'software-testing-analysis',
    title: '(Uni) Software Testing and Analysis',
    shortDescription: 'Explored QA processes, test design, and software analysis techniques.',
    fullDescription: 'Comprehensive study and implementation of software testing methodologies, including functional testing, structural analysis, and quality assurance processes using industry-standard tools and frameworks.',
    category: 'academic',
    projectCategory: 'software',
    technologies: ['Software Testing', 'QA Processes', 'Test Design', 'Documentation'],
    githubUrl: 'https://github.com/id-nynt/250019_matplotlib-test',
    team: 'Academic team project',
    role: 'Team Coordinator',
    responsibilities: [
      'Coordinated team meetings and progress tracking',
      'Managed communication with tutors',
      'Structured test planning and documentation',
      'Applied functional, structural, and analytic testing concepts'
    ],
    outcomes: [
      'Achieved 37.45/40 for well-structured report',
      'Effective presentation delivery',
      'Comprehensive understanding of testing methodologies'
    ],
    period: '04/2025 - 05/2025',
    imageUrl: '/images/projects/software-testing.png',
    featured: false,
    status: 'completed'
  }
]

// Helper functions for mock data
export const getMockProjects = () => mockProjects

export const getMockProjectById = (id: string) => {
  return mockProjects.find(project => project.id === id)
}

export const getMockProjectsByCategory = (category: 'academic' | 'professional' | 'all') => {
  if (category === 'all') return mockProjects
  return mockProjects.filter(project => project.category === category)
}

export const getMockProjectsByType = (projectCategory: 'software' | 'data-ml' | 'cloud-networking' | 'all') => {
  if (projectCategory === 'all') return mockProjects
  return mockProjects.filter(project => project.projectCategory === projectCategory)
}

export const getFeaturedProjects = () => {
  return mockProjects.filter(project => project.featured)
}